name: Rust solutions

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: rust/

jobs:
  ci:
    name: Lint, build and test solutions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-latest"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.6
        with:
          submodules: true

      - name: Use Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --check

      - name: Build solutions
        run: cargo build --verbose

      - name: Test solutions
        run: cargo test --verbose
